services:
  # Laravel Backend
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db

  # Composer Container
  composer:
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    entrypoint: ["composer"]

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: otakumart
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  # React Frontend (Production build)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-prod
    ports:
      - "8080:8080"

volumes:
  dbdata:
  node_modules:

